/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ProtectedPendingApprovalRouteImport } from './routes/_protected/pending-approval'
import { Route as ProtectedEnrollmentsRouteImport } from './routes/_protected/enrollments'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgetPasswordRouteImport } from './routes/_auth/forget-password'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedMyCoursesIndexRouteImport } from './routes/_protected/my-courses/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedCoursesIndexRouteImport } from './routes/_protected/courses/index'
import { Route as ProtectedMyCoursesCourseIdRouteImport } from './routes/_protected/my-courses/$courseId'
import { Route as ProtectedCoursesCreateRouteImport } from './routes/_protected/courses/create'
import { Route as ProtectedCoursesCourseIdIndexRouteImport } from './routes/_protected/courses/$courseId.index'
import { Route as ProtectedCoursesCourseIdEnrollmentsRouteImport } from './routes/_protected/courses/$courseId.enrollments'
import { Route as ProtectedCoursesCourseIdAttendanceRouteImport } from './routes/_protected/courses/$courseId.attendance'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPendingApprovalRoute =
  ProtectedPendingApprovalRouteImport.update({
    id: '/pending-approval',
    path: '/pending-approval',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedEnrollmentsRoute = ProtectedEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyCoursesIndexRoute = ProtectedMyCoursesIndexRouteImport.update({
  id: '/my-courses/',
  path: '/my-courses/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCoursesIndexRoute = ProtectedCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyCoursesCourseIdRoute =
  ProtectedMyCoursesCourseIdRouteImport.update({
    id: '/my-courses/$courseId',
    path: '/my-courses/$courseId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCoursesCreateRoute = ProtectedCoursesCreateRouteImport.update({
  id: '/courses/create',
  path: '/courses/create',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCoursesCourseIdIndexRoute =
  ProtectedCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCoursesCourseIdEnrollmentsRoute =
  ProtectedCoursesCourseIdEnrollmentsRouteImport.update({
    id: '/courses/$courseId/enrollments',
    path: '/courses/$courseId/enrollments',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCoursesCourseIdAttendanceRoute =
  ProtectedCoursesCourseIdAttendanceRouteImport.update({
    id: '/courses/$courseId/attendance',
    path: '/courses/$courseId/attendance',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/enrollments': typeof ProtectedEnrollmentsRoute
  '/pending-approval': typeof ProtectedPendingApprovalRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/courses/create': typeof ProtectedCoursesCreateRoute
  '/my-courses/$courseId': typeof ProtectedMyCoursesCourseIdRoute
  '/courses': typeof ProtectedCoursesIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/my-courses': typeof ProtectedMyCoursesIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/courses/$courseId/attendance': typeof ProtectedCoursesCourseIdAttendanceRoute
  '/courses/$courseId/enrollments': typeof ProtectedCoursesCourseIdEnrollmentsRoute
  '/courses/$courseId': typeof ProtectedCoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/enrollments': typeof ProtectedEnrollmentsRoute
  '/pending-approval': typeof ProtectedPendingApprovalRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/courses/create': typeof ProtectedCoursesCreateRoute
  '/my-courses/$courseId': typeof ProtectedMyCoursesCourseIdRoute
  '/courses': typeof ProtectedCoursesIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/my-courses': typeof ProtectedMyCoursesIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/courses/$courseId/attendance': typeof ProtectedCoursesCourseIdAttendanceRoute
  '/courses/$courseId/enrollments': typeof ProtectedCoursesCourseIdEnrollmentsRoute
  '/courses/$courseId': typeof ProtectedCoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_auth/forget-password': typeof AuthForgetPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/enrollments': typeof ProtectedEnrollmentsRoute
  '/_protected/pending-approval': typeof ProtectedPendingApprovalRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/_protected/courses/create': typeof ProtectedCoursesCreateRoute
  '/_protected/my-courses/$courseId': typeof ProtectedMyCoursesCourseIdRoute
  '/_protected/courses/': typeof ProtectedCoursesIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/my-courses/': typeof ProtectedMyCoursesIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
  '/_protected/courses/$courseId/attendance': typeof ProtectedCoursesCourseIdAttendanceRoute
  '/_protected/courses/$courseId/enrollments': typeof ProtectedCoursesCourseIdEnrollmentsRoute
  '/_protected/courses/$courseId/': typeof ProtectedCoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/forget-password'
    | '/login'
    | '/sign-up'
    | '/enrollments'
    | '/pending-approval'
    | '/reset-password/$token'
    | '/courses/create'
    | '/my-courses/$courseId'
    | '/courses'
    | '/dashboard'
    | '/my-courses'
    | '/users'
    | '/courses/$courseId/attendance'
    | '/courses/$courseId/enrollments'
    | '/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/forget-password'
    | '/login'
    | '/sign-up'
    | '/enrollments'
    | '/pending-approval'
    | '/reset-password/$token'
    | '/courses/create'
    | '/my-courses/$courseId'
    | '/courses'
    | '/dashboard'
    | '/my-courses'
    | '/users'
    | '/courses/$courseId/attendance'
    | '/courses/$courseId/enrollments'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/logout'
    | '/_auth/forget-password'
    | '/_auth/login'
    | '/_auth/sign-up'
    | '/_protected/enrollments'
    | '/_protected/pending-approval'
    | '/reset-password/$token'
    | '/_protected/courses/create'
    | '/_protected/my-courses/$courseId'
    | '/_protected/courses/'
    | '/_protected/dashboard/'
    | '/_protected/my-courses/'
    | '/_protected/users/'
    | '/_protected/courses/$courseId/attendance'
    | '/_protected/courses/$courseId/enrollments'
    | '/_protected/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/pending-approval': {
      id: '/_protected/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof ProtectedPendingApprovalRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/enrollments': {
      id: '/_protected/enrollments'
      path: '/enrollments'
      fullPath: '/enrollments'
      preLoaderRoute: typeof ProtectedEnrollmentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forget-password': {
      id: '/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-courses/': {
      id: '/_protected/my-courses/'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof ProtectedMyCoursesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/': {
      id: '/_protected/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof ProtectedCoursesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-courses/$courseId': {
      id: '/_protected/my-courses/$courseId'
      path: '/my-courses/$courseId'
      fullPath: '/my-courses/$courseId'
      preLoaderRoute: typeof ProtectedMyCoursesCourseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/create': {
      id: '/_protected/courses/create'
      path: '/courses/create'
      fullPath: '/courses/create'
      preLoaderRoute: typeof ProtectedCoursesCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/$courseId/': {
      id: '/_protected/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof ProtectedCoursesCourseIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/$courseId/enrollments': {
      id: '/_protected/courses/$courseId/enrollments'
      path: '/courses/$courseId/enrollments'
      fullPath: '/courses/$courseId/enrollments'
      preLoaderRoute: typeof ProtectedCoursesCourseIdEnrollmentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/$courseId/attendance': {
      id: '/_protected/courses/$courseId/attendance'
      path: '/courses/$courseId/attendance'
      fullPath: '/courses/$courseId/attendance'
      preLoaderRoute: typeof ProtectedCoursesCourseIdAttendanceRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedEnrollmentsRoute: typeof ProtectedEnrollmentsRoute
  ProtectedPendingApprovalRoute: typeof ProtectedPendingApprovalRoute
  ProtectedCoursesCreateRoute: typeof ProtectedCoursesCreateRoute
  ProtectedMyCoursesCourseIdRoute: typeof ProtectedMyCoursesCourseIdRoute
  ProtectedCoursesIndexRoute: typeof ProtectedCoursesIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedMyCoursesIndexRoute: typeof ProtectedMyCoursesIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
  ProtectedCoursesCourseIdAttendanceRoute: typeof ProtectedCoursesCourseIdAttendanceRoute
  ProtectedCoursesCourseIdEnrollmentsRoute: typeof ProtectedCoursesCourseIdEnrollmentsRoute
  ProtectedCoursesCourseIdIndexRoute: typeof ProtectedCoursesCourseIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedEnrollmentsRoute: ProtectedEnrollmentsRoute,
  ProtectedPendingApprovalRoute: ProtectedPendingApprovalRoute,
  ProtectedCoursesCreateRoute: ProtectedCoursesCreateRoute,
  ProtectedMyCoursesCourseIdRoute: ProtectedMyCoursesCourseIdRoute,
  ProtectedCoursesIndexRoute: ProtectedCoursesIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedMyCoursesIndexRoute: ProtectedMyCoursesIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
  ProtectedCoursesCourseIdAttendanceRoute:
    ProtectedCoursesCourseIdAttendanceRoute,
  ProtectedCoursesCourseIdEnrollmentsRoute:
    ProtectedCoursesCourseIdEnrollmentsRoute,
  ProtectedCoursesCourseIdIndexRoute: ProtectedCoursesCourseIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
